### PR TITLE
Added timeout option when executing consumer

### PR DESCRIPTION
**Pull request by ludekvesely**
Hi, I've added timeout option for consumers. In the following example consumer will end after 10 seconds:

```
php www/index.php rabbitmq:consumer -t 10 myConsumer
```

I've added it because I need to limit how long are consumers running. I've tried option `-m` but it doesn't wirk when queue is empty. Currently i run php with max_execution_time option but it is not a good solution.

### CODE REVIEW

**Comment by fprochazka** [comment]
Great work, but I'm not sure about the motivation. Do you really think it's a good idea to restart the worker every 10 seconds? I have them running for days without the slightest problem. 

For example doctrine has a `ping()` function that you can use for reconnect. I simply have this block of code in every consumer that works with database.

```php
if ($db->ping() === FALSE) {
	$db->close();
	$db->connect();
}
```

and boom, no need to restart :)

**Comment by fprochazka** [comment]
Also, there is already a `idleTimeout`. If you hook onto the consumer (for example with kdyby/events), you can simply terminate the script, if there has been no message processed for the given amount of time.

```php
$consumer->onTimeout[] = function () {
    throw new \Kdyby\RabbitMq\TerminateException; // this a custom exception that will force the consumer to shut down gracefuly
};
```

**Comment by ludekvesely** [comment]
Thank you for reply! I used RabbitMq without Kdyby library in my older project and I had to restart workers after some time (longer than 10 seconds, it was just an example) without work and I didn't know how to do it with this library. I will try `onTimeout` with kdyby/events, it looks ok and solves my problem. 

Btw I think that using doctrine's ping method in every consumed message is not a good solution. How do you know that connection wasn't lost between ping and following query? Also it must slow down database - every consumed message means one more query..

**Comment by fprochazka** [comment]
@ludekvesely ping is done on the beginning of consuming a message, so unless the database dies, there is really no way for the connection to be lost.

**Comment by ludekvesely** [comment]
Thank you for reply, I'm closing this PR.

**Pull request closed without merging**
